// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxx:web:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxx',
    projectId: 'imnagerncy-dev',
    authDomain: 'imnagerncy-dev.firebaseapp.com',
    storageBucket: 'imnagerncy-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxx:android:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxx',
    projectId: 'imnagerncy-dev',
    storageBucket: 'imnagerncy-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxx:ios:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxx',
    projectId: 'imnagerncy-dev',
    storageBucket: 'imnagerncy-dev.appspot.com',
    iosBundleId: 'com.imnagerncy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:xxxxxxxxxx:macos:xxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxx',
    projectId: 'imnagerncy-dev',
    storageBucket: 'imnagerncy-dev.appspot.com',
    iosBundleId: 'com.imnagerncy.app',
  );
}
